#!/usr/bin/env python

# Author:       Buster Major
# UPI:          bmaj406
# Date:         5/08/2018

import os
import re
import sys

if __name__ == '__main__':

    def _full_path(xroot, partial):
        if partial.startswith("/"):
            partial = partial[1:]
        path = os.path.join(xroot, partial)
        return path

    filename, ext = os.path.splitext(sys.argv[1])
    root = os.path.join(os.getcwd(), '.versiondir/versions')
    filename = filename[1:] if filename.startswith('/') else filename

    # Loop through and add all version numbers in [...] for filename to a list
    version_list = []
    for i in os.listdir(root):
        m = re.match('.' + filename + '\\[(\\d*)\\]' + ext, i)
        if m:
            version_list.append(m.group(1))

    if len(version_list) < int(sys.argv[2]):
        print "You don't have that many versions."
        exit(1)

    # Sort versioned files in directory descending, as requirement states lower numbers input from command
    # line correspond to higher version numbers
    version_list.sort(reverse=True)
    print open(_full_path(root, '.' + filename + '[' + version_list[int(sys.argv[2]) - 1] + ']' + ext)).read()
