#!/usr/bin/env python

import os
import sys
import re
if __name__ == '__main__':

    def _full_path(xroot, partial):
        if partial.startswith("/"):
            partial = partial[1:]
        path = os.path.join(xroot, partial)
        return path

    filename, ext = os.path.splitext(sys.argv[1])
    root = os.path.join(os.getcwd(), '.versiondir/versions')
    filename = filename[1:] if filename.startswith('/') else filename

    max_version = 0
    version_list = []
    for i in os.listdir(root):
        m = re.match('.' + filename + '\\[(\\d*)\\]' + ext, i)
        if m:
            version_list.append(m.group(1))
            max_version = int(m.group(1)) if max_version < int(m.group(1)) else max_version

    for i in version_list:
        if int(i) is not max_version:
            os.remove(_full_path(root, '.' + filename + '[' + i + ']' + ext))
